create database project_customer_shopping_behaviour_analysis;


use project_customer_shopping_behaviour_analysis;


select * from customer_shopping LIMIT 10;


-- Q1. what is the total revenue generated by male vs female customers?
SELECT gender, sum(purchase_amount) as total_revenue
from customer_shopping
group by gender;


-- Q2. which customers used a discount but still spent more than the avg purchase amount?
select customer_id,purchase_amount
from customer_shopping
where discount_applied = 'Yes' 
	and purchase_amount >= (
		select avg(purchase_amount)
        from customer_shopping
	);
    

-- Q3. which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as "average product rating"
from customer_shopping
group by item_purchased 
order by avg(review_rating) desc
limit 5;


-- Q4. compare the average purchase amounts between standard and express shipping.
select shipping_type, avg(purchase_amount)
from customer_shopping
where shipping_type in ('Standard','Express')
group by shipping_type;


-- Q5. Do subscribe customers spend more? 
-- compare average spend and total revenue between subscribers and non-subscribers
select subscription_status, 
count(customer_id) as total_customer,
avg(purchase_amount) as avg_spend , 
sum(purchase_amount) as total_revenue
from customer_shopping
group by subscription_status;


-- Q6. which 5 products have the highest percentage of purchase with discount applied?
SELECT
    item_purchased,
    ROUND(
        100 * SUM(CASE
                    WHEN discount_applied = 'Yes' THEN 1
                    ELSE 0
                  END) / COUNT(*), 2
    ) AS discount_rate
FROM customer_shopping
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7.Segment customer into new, returning, and loyal based on their total number of previous purchases, 
-- and show the count of each segment?
SELECT
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer_shopping
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
SELECT *
FROM (
    SELECT
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS item_rank,
        category,
        item_purchased,
        COUNT(*) AS purchase_count
    FROM customer_shopping
    GROUP BY category, item_purchased
) AS ranked_products
WHERE item_rank <= 3
ORDER BY category, item_rank;


-- Q9. Are customer who are repeat buyers (more than 5 previous purchase) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping
where previous_purchases > 5
group by subscription_status;



-- Q10. What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as revenue_contribution
from customer_shopping
group by age_group
order by  revenue_contribution  desc;